config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # categories
  get 'categories', to: 'categories#index', as: :category_index
  get 'categories/:id', to: 'categories#show', as: :category_show

  # hobbies
  get 'hobbies/:id', to: 'hobbies#show', as: :hobby_show
  post 'hobbies/:id', to: 'hobbies#add', as: :hobby_add

  #communities
  get 'hobbies/:id/communities', to: 'communities#index', as: :community_index
  get 'hobbies/:id/communities/new', to: 'communities#new', as: :community_new
  post 'hobbies/:id/communities/create', to: 'communities#create', as: :community_create
  delete 'hobbies/:id/communities/delete', to: 'communities#delete', as: :community_delete
  get 'community/:id', to: 'communities#show', as: :community_show
  post 'community/:id', to: 'communities#add', as: :community_add
   #board_comments
   post 'community/:id/board_comments', to: 'board_comments#add', as: :board_comment_add
   delete 'community/:id/board_comments', to: 'board_comments#delete', as: :board_comment_delete

  #matchings
  get 'matching', to: 'matching#show', as: :matching_show
  get 'matching/result', to: 'matching#result_show', as: :matching_result_show

  #rankings
  get 'rankings', to: 'rankings#index', as: :ranking_index

  # home
  root to: 'home#index'

  # users
  resources :users, only: [:show, :edit, :update]
   #hobbies
   get 'users/:id/hobby/:hobby_id', to: 'users#hobby_index', as: :users_hobby
   delete 'users/:id/hobby/:hobby_id', to: 'users#hobby_delete', as: :users_hobby_delete
   #communities
   delete 'users/:id/hobby/:hobby_id/community/:community_id', to: 'users#community_delete', as: :users_community_delete
   #records
   post 'users/:id/hobby/:hobby_id/record', to: 'users#record_create', as: :users_record
   delete 'users/:id/hobby/:hobby_id/record', to: 'users#record_delete', as: :users_record_delete
   #cancel
   get '/users/cancel/show', to: 'users#cancel_show', as: :users_cancel_show
   delete '/users/cancel/show', to: 'users#cancel_delete', as: :users_cancel_delete

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attachment :image

  has_many :users_hobbies
  has_many :hobbies, through: :users_hobbies
  has_many :users_communities
  has_many :communities, through: :users_communities
  has_many :records
  has_many :board_comments

  validates :name, presence: true
  validates :age, presence: true
  validates :sex, presence: true
  validates :job, presence: true
  validates :address, presence: true
  validates :email, presence: true
  validates :introduction, length: { maximum: 200 }
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
  	@user = User.find(params[:id])
    @hobbies = UsersHobby.where(user_id: @user.id).page(params[:page]).per(5)
    @communities = UsersCommunity.where(user_id: @user.id)
  end

  def hobby_delete
    uh = UsersHobby.find(params[:hobby_id])
    if uh.destroy
      flash[:notice] = "趣味を削除しました"
      redirect_to user_path
    else
      flash[:notice] = "趣味の削除に失敗しました"
      redirect_to user_path
    end
  end

  def community_delete
    uci = params[:users_community_id]
    uc = UsersCommunity.find(uci)
    if uc.destroy
      flash[:notice] = "趣味を削除しました"
      redirect_to user_path
    else
      flash[:notice] = "趣味の削除に失敗しました"
      redirect_to user_path
    end
  end


  def edit
  	@user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def hobby_index
    @user = User.find(params[:id])
    @hobby = Hobby.find(params[:hobby_id])
    @total = Record.where(user_id: @user.id).where(hobby_id: @hobby.id).pluck(:time)
    @record = Record.new
    @records = Record.where(user_id: @user.id).where(hobby_id: @hobby.id).order('date ASC').group(:date).sum(:time)
    @rec = Record.where(user_id: @user.id).where(hobby_id: @hobby.id).order('date ASC').page(params[:page]).per(5)
  end

  def record_create
    user = params[:user_id]
    hobby = params[:hobby_id]
    record = Record.new(record_params)
    record.user_id = user
    record.hobby_id = hobby
    if record.save
      flash[:notice] = "活動を記録しました"
      redirect_to users_hobby_path(user)
    else
      flash[:notice] = "エラー：入力に誤りがあります"
      redirect_to users_hobby_path(user)
    end
  end

  def record_delete
    record = Record.find(params[:record_id])
    record.destroy
    flash[:notice] = "記録を削除しました"
    redirect_to users_hobby_path(params[:id])
  end

  def cancel_show
  end

  def cancel_delete
    user = User.find(current_user.id)
    user.destroy
    flash[:notice] = "退会しました"
    redirect_to root_path
  end

  private
  def user_params
    params.require(:user).permit(:name, :address, :sex, :age, :job, :email, :password, :image, :introduction)
  end
  def record_params
    params.require(:record).permit(:time, :date, :comment)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/cancel_show.html.erb
<main>
  <div class="container">
    <div class="row my-lg-4">
      <div class="col-lg-2 offset-lg-2">
        <h3>退会</h3>
      </div>
    </div>
    <div class="row">
      <p class="col-lg-8 offset-lg-4">退会されると今までのユーザ情報、<br>
      活動記録等は失われますがよろしいでしょうか？
      </p>
    </div>
    <div class="row">
        <div class="col-lg-1 offset-lg-4">
        <%= link_to '退会する', users_cancel_show_path, method: :delete, class: 'btn btn-light' %>
        </div>
        <div class="col-lg-1 offset-lg-1">

        <%= link_to '退会しない', user_path(current_user.id), class: 'btn btn-light' %>
        </div>
    </div>
  </div>
</main>

app/views/users/edit.html.erb
<div class="container">
  <div class="edit">
    <div class="row my-lg-3">
      <div class="col-md"></div>
      <div class="col-md-10">
        <br>
        <h1>プロフィール編集</h1>
        <%= form_for(@user) do |f| %>
          <%= render "layouts/error_messages", model: f.object %>
          <div class="form-group">
            <%= f.label :name %><br>
            <%= f.text_field :name %>
          </div>
          <div class="form-group">
            <%= f.label :age %><br>
            <%= f.select :age, [["20歳未満", "10"], ["20代", "20"],["30代", "30"], ["40代", "40"],["50代", "50"], ["60代", "60"],["70代", "70"], ["80代", "80"],["90歳以上", "90"]],:prompt => "選択" %>
          </div>
          <div class="form-group">
            <%= f.label :sex %><br>
            <%= f.select :sex, [["男性", "男性"], ["女性", "女性"]],:prompt => "選択" %>
          </div>
          <div class="form-group">
            <%= f.label :job %><br>
            <%= f.select :job, [["公務員", "公務員"], ["経営者・役員", "経営者・役員"],["会社員", "会社員"], ["自営業", "自営業"],["自由業", "自由業"], ["専業主婦", "専業主婦"],["パート・アルバイト", "パート・アルバイト"], ["学生", "学生"],["その他", "その他"]],:prompt => "選択" %>
          </div>
          <div class="form-group">
            <%= f.label :address %><br>
            <%= f.select :address, [["北海道", "北海道"], ["東北", "東北"],["関東", "関東"], ["中部", "中部"],["近畿", "近畿"], ["中国", "中国"],["四国", "四国"], ["九州", "九州"]],:prompt => "選択" %>
          </div>
          <div class="form-group">
            <%= f.label :email %><br>
            <%= f.text_field :email %>
          </div>
          <div class="form-group">
          </div>
          <div class="form-group">
            <%= attachment_image_tag @hobby, :image, :fill, 100, 100, format: "jpg", :size => "100x100", fallback: "no-category-image.jpg" %>
            <%= f.label :image %><br>
            <%= f.attachment_field :image, placeholder: "profile_image" %>
          </div>
          <div class="form-group">
            <%= f.label :introduction %><br>
            <%= f.text_field :introduction, :size => "50x10", placeholder: "始めたいことや目標を記入してください" %>
          </div>
          <div class="form-action">
            <%= f.submit "プロフィール更新", class: "btn btn-primary" %>
          </div>
        <% end %>
        <br>
        <div class="cancel">
          <%= link_to "退会", users_cancel_show_path, class: "btn btn-danger" %>
        </div>
        <br>
        <div class="back">
          <%= link_to "戻る", user_path(@user), class: "btn btn-light" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/hobby_index.html.erb
<main>
  <div class="container">
  	<p class="notice"><%= notice %></p>
  	<%= render 'layouts/sidebar', user: @user %>
  </div>
  <br>
  <br>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-5">
        <h3>趣味名： <%= @hobby.name %></h3>
      </div>
      <div class="col-lg-5">
        <h3>総活動時間： <%= @total.sum %>時間</h3>
      </div>
    </div>
    <br>
    <div class="row justify-content-center">
      <div class="col-lg-12">
        <%= area_chart @records, min: 0, max: 12, height: "500px", width: "1100px", colors: ["orange", "#999"], messages: {empty: "データがありません"}, xtitle: "活動日", ytitle: "時間",label: "時間", discrete: true %><br>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-lg-12">
        <table class="table">
         <thead>
           <tr>
            <th>活動日</th>
            <th>活動時間</th>
            <th>特記事項</th>
          </tr>
        </thead>
        <% @rec.each do |record| %>
        <tbody>
          <tr>
            <td><%= record.date %></td>
            <td><%= record.time %>時間</td>
            <td><%= record.comment %></td>
          <% if current_user.id == @user.id or current_user.admin? %>
            <td><%= link_to '削除', users_record_delete_path(user_id: @user, record_id: record.id), method: :delete, class: 'btn btn-primary btn-xs', "data-confirm" => "Are you sure?" %></td>
          <% end %>
          </tr>
         </tbody>
        <% end %>
        </table>
      </div>
    <%= paginate @rec %>
    </div>
    <br>
    <br>
    <br>
  </div>
  <div class="container">
    <% if current_user.id == @user.id %>
    <div class="row justify-content-center">
      <div class="col-lg-10">
        <h3>活動を記録する</h3>
        <br>
      </div>
    </div>
    <%= form_for(@record, url: users_record_path(user_id: @user, hobby_id: @hobby)) do |f| %>
    <div class="row justify-content-center">
      <div class="col-lg-5">
        <h5>活動日</h5>
        <div class="field">
          <%= f.text_field :date, :size=>"20x10", placeholder: "2019-01-01" %>
        </div>
      </div>
      <div class="col-lg-5">
        <h5>活動時間</h5>
        <div class="field">
          <%= f.text_field :time, :size=>"3x10", placeholder: "2" %>時間
        </div>
      </div>
    </div>
    <br>
    <div class="row justify-content-center">
      <div class="col-lg-10">
        <h5>特記事項</h5>
        <div class="field">
          <%= f.text_field :comment, :size=>"80x10", placeholder: "できるようになったことなど（任意）" %>
        </div>
        <br>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-lg-10">
        <div class="action">
          <%= f.submit "投稿する", class: "btn btn-primary btn-xs" %>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</main>

app/views/users/show.html.erb
<body>
  <div class="container">
   <p class="notice"><%= notice %></p>
     <%= render 'layouts/sidebar', user: @user %>
  </div>
  <br>
  <br>
  <!-- 活動中の趣味一覧 -->
  <div class="container">
    <div class="row justify-content-lg-center">
      <div class="col-lg-12">
        <h3 class="joined-hobbies">活動中の趣味</h3>
      <% if !@hobbies.empty?  %>
        <table class="table">
          <thead>
            <tr>
              <th>イメージ</th>
              <th>趣味</th>
              <th>紹介文</th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <% @hobbies.each do |hobby| %>
          <tbody>
            <tr>
              <td><%= attachment_image_tag hobby.hobby, :image, :fill, 200, 200, :size => "100x100", fallback: "no-category-image.jpg" %></td>
              <td><%= link_to hobby_show_path(hobby.hobby.id) do %><%= hobby.hobby.name %><% end %></td>
              <td><%= hobby.hobby.introduction %></td>
              <td><%= link_to "活動詳細", users_hobby_path(hobby_id: hobby.hobby.id), class: "btn btn-primary btn-xs" %></td>
              <td><% if current_user.id == hobby.user_id %>
                <%= link_to "削除", users_hobby_delete_path(hobby_id: hobby.id),method: :delete, class: "btn btn-light btn-xs", "data-confirm" => "Are you sure?" %>
              <% end %></td>
            </tr>
            <% end %>
          <% else %>
          <ul class="list-group-item">
            <div>
             現在、活動中の趣味はありません。
            </div>
          </ul>
          </tbody>
          <% end %>
        </table>
      </div>
      <%= paginate @hobbies %>
    </div>
  </div>
  <br>
  <br>
  <!-- 参加中のチャレンジ一覧 -->
  <div class="container">
    <div class="row justify-content-lg-center">
      <div class="col-lg-12">
        <h3 class="joined-challenges">参加中のチャレンジ</h3>
      <% if !@communities.empty?  %>
        <table class="table">
          <thead>
            <tr>
              <th>趣味名</th>
              <th>チャレンジ名</th>
              <th>難易度</th>
              <th>紹介文</th>
              <th></th>
            </tr>
          </thead>
          <% @communities.each do |community| %>
          <tbody>
            <tr>
              <td><%= link_to hobby_show_path(community.community.hobby.id) do %><%= community.community.hobby.name %><% end %></td>
              <td><%= link_to community_show_path(community.community.id) do %><%= community.community.name %><% end %></td>
              <td><%= community.community.level %></td>
              <td><%= community.community.introduction %></td>
              <% if current_user.id == community.user_id %>
              <td><%= link_to "削除", users_community_delete_path(users_community_id: community.id, hobby_id: community.community.hobby.id, community_id: community.community.id),method: :delete, class: "btn btn-light btn-xs", "data-confirm" => "Are you sure?" %></td>
              <% end %>
            </tr>
            <% end %>
          <% else %>
          <ul class="list-group-item">
            <div>
             現在、参加中のチャレンジはありません。
            </div>
          </ul>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
</body>