config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # categories
  get 'categories', to: 'categories#index', as: :category_index
  get 'categories/:id', to: 'categories#show', as: :category_show

  # hobbies
  get 'hobbies/:id', to: 'hobbies#show', as: :hobby_show
  post 'hobbies/:id', to: 'hobbies#add', as: :hobby_add

  #communities
  get 'hobbies/:id/communities', to: 'communities#index', as: :community_index
  get 'hobbies/:id/communities/new', to: 'communities#new', as: :community_new
  post 'hobbies/:id/communities/create', to: 'communities#create', as: :community_create
  delete 'hobbies/:id/communities/delete', to: 'communities#delete', as: :community_delete
  get 'community/:id', to: 'communities#show', as: :community_show
  post 'community/:id', to: 'communities#add', as: :community_add
   #board_comments
   post 'community/:id/board_comments', to: 'board_comments#add', as: :board_comment_add
   delete 'community/:id/board_comments', to: 'board_comments#delete', as: :board_comment_delete

  #matchings
  get 'matching', to: 'matching#show', as: :matching_show
  get 'matching/result', to: 'matching#result_show', as: :matching_result_show

  #rankings
  get 'rankings', to: 'rankings#index', as: :ranking_index

  # home
  root to: 'home#index'

  # users
  resources :users, only: [:show, :edit, :update]
   #hobbies
   get 'users/:id/hobby/:hobby_id', to: 'users#hobby_index', as: :users_hobby
   delete 'users/:id/hobby/:hobby_id', to: 'users#hobby_delete', as: :users_hobby_delete
   #communities
   delete 'users/:id/hobby/:hobby_id/community/:community_id', to: 'users#community_delete', as: :users_community_delete
   #records
   post 'users/:id/hobby/:hobby_id/record', to: 'users#record_create', as: :users_record
   delete 'users/:id/hobby/:hobby_id/record', to: 'users#record_delete', as: :users_record_delete
   #cancel
   get '/users/cancel/show', to: 'users#cancel_show', as: :users_cancel_show
   delete '/users/cancel/show', to: 'users#cancel_delete', as: :users_cancel_delete

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    if user.try(:admin?)
        can :access, :rails_admin
        can :manage, :all
    #   else
    #     can :read, :all
    end
  end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board_comment.rb
class BoardComment < ApplicationRecord
  belongs_to :community
  belongs_to :user

  validates :comment, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  attachment :image

  has_many :hobbies

  validates :category, presence: true
end

app/models/community.rb
class Community < ApplicationRecord
  has_many :board_comments
  has_many :users_communities
  has_many :users, through: :users_communities
  belongs_to :hobby

  validates :name, presence: true
  validates :level, presence: true
  validates :introduction, length: {in: 2..20}, presence: true
end

app/models/first_step.rb
class FirstStep < ApplicationRecord
  belongs_to :hobby

  validates :item, presence: true
  validates :cost, presence: true
  validates :introduction, presence: true
end

app/models/hobbies_rating.rb
class HobbiesRating < ApplicationRecord
  belongs_to :hobby
  belongs_to :rating

  validates :point, presence: true
end

app/models/hobby.rb
class Hobby < ApplicationRecord

  attachment :image

  has_many :users_hobbies, dependent: :destroy
  has_many :users, through: :users_hobbies
  has_many :records
  has_many :communities
  belongs_to :category
  has_many :hobbies_ratings
  has_many :ratings, through: :hobbies_ratings
  has_one :first_step

end

app/models/rating.rb
class Rating < ApplicationRecord
  has_many :hobbies_ratings
  has_many :hobbies, through: :hobbies_ratings

  validates :name, presence: true
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
  belongs_to :hobby

  validates :time, presence: true
  validates :date, presence: true
  validates :comment, length: {in: 0..50}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attachment :image

  has_many :users_hobbies
  has_many :hobbies, through: :users_hobbies
  has_many :users_communities
  has_many :communities, through: :users_communities
  has_many :records
  has_many :board_comments

  validates :name, presence: true
  validates :age, presence: true
  validates :sex, presence: true
  validates :job, presence: true
  validates :address, presence: true
  validates :email, presence: true
  validates :introduction, length: { maximum: 200 }
end

app/models/users_community.rb
class UsersCommunity < ApplicationRecord
  belongs_to :user
  belongs_to :community
end

app/models/users_hobby.rb
class UsersHobby < ApplicationRecord
  belongs_to :user
  belongs_to :hobby
end

app/controllers/hobbies_controller.rb
class HobbiesController < ApplicationController
before_action :authenticate_user!, :only => [:show, :index]
  def show
  	@hobby = Hobby.find(params[:id])
    @people = UsersHobby.where(hobby_id: @hobby.id).count(:hobby_id)
  end

  def add
  	hobby = Hobby.find(params[:id])
  	user = current_user
  	uh = UsersHobby.new
  	uh.user_id = user.id
  	uh.hobby_id = hobby.id
  	if uh.save
  		flash[:notice] = "趣味に追加しました"
  		redirect_to hobby_show_path
  	else
  	  flash[:notice] = "エラー：ログインしてください"
      redirect_to hobby_show_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/hobbies_helper.rb
module HobbiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/matching_helper.rb
module MatchingHelper
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hobbies/show.html.erb
<main>
<div class="container">
    <% if flash[:notice] %>
    <%= flash[:notice] %>
    <% end %>
</div>
<div class="container">
      <div class="row justify-content-center">
      	<div class="col-lg-3">
          	<div class="hobby_image">
          		<%= attachment_image_tag @hobby, :image, :fill, 250, 250, :size => "250x250", fallback: "no-category-image.jpg" %>
          	</div>
        	</div>
        	<div class="col-lg-6">
        		<h5 class="category_name">カテゴリー &nbsp <u><%= @hobby.category.category %></u></h5><br>
        		<h5 class="hobby_name">趣味名 &nbsp <u><%= @hobby.name %></u></h5><br>
            <h5 class="people">参加者 &nbsp <u><%= @people %>人</u></h5><br>
          	<div class="card">
            		<div class="card-body">
              		<%= @hobby.introduction %>
            		</div>
          	</div>
        	</div>
          <div class="col-lg-3">
            <%= link_to "趣味に追加する", hobby_add_path(@hobby), method: :post, class: "btn btn-primary btn-xs" %>
            <br>
            <br>
            <%= link_to "チャレンジ一覧", community_index_path, class: "btn btn-primary btn-xs" %>
          </div>
      </div>
      <br>
      <br>
      <div class="row">
      	<div class="col-lg-6">
          <h3 class="black_band"><%= @hobby.name %>の始め方</h3>
        </div>
        <div class="col-lg-6">
          <h3 class="black_band">始めるにあたり</h3>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-6">
          <br>
          <h4><%= @hobby.first_step.introduction %></h4>
        </div>
        <div class="col-lg-6">
          <br>
          <h4>&nbsp必要アイテム:</h4>
          <h5>&nbsp&nbsp<%= @hobby.first_step.item %></h5>
          <br>
          <h4>&nbsp費用目安:</h4>
          <h5>&nbsp&nbsp¥ <%= @hobby.first_step.cost %>〜</h5>
      	</div>

      </div>
  </div>
<br>
<br>
<br>
<br>
<br>
</main>