config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # categories
  get 'categories', to: 'categories#index', as: :category_index
  get 'categories/:id', to: 'categories#show', as: :category_show

  # hobbies
  get 'hobbies/:id', to: 'hobbies#show', as: :hobby_show
  post 'hobbies/:id', to: 'hobbies#add', as: :hobby_add

  #communities
  get 'hobbies/:id/communities', to: 'communities#index', as: :community_index
  get 'hobbies/:id/communities/new', to: 'communities#new', as: :community_new
  post 'hobbies/:id/communities/create', to: 'communities#create', as: :community_create
  delete 'hobbies/:id/communities/delete', to: 'communities#delete', as: :community_delete
  get 'community/:id', to: 'communities#show', as: :community_show
  post 'community/:id', to: 'communities#add', as: :community_add
   #board_comments
   post 'community/:id/board_comments', to: 'board_comments#add', as: :board_comment_add
   delete 'community/:id/board_comments', to: 'board_comments#delete', as: :board_comment_delete

  #matchings
  get 'matching', to: 'matching#show', as: :matching_show
  get 'matching/result', to: 'matching#result_show', as: :matching_result_show

  #rankings
  get 'rankings', to: 'rankings#index', as: :ranking_index

  # home
  root to: 'home#index'

  # users
  resources :users, only: [:show, :edit, :update]
   #hobbies
   get 'users/:id/hobby/:hobby_id', to: 'users#hobby_index', as: :users_hobby
   delete 'users/:id/hobby/:hobby_id', to: 'users#hobby_delete', as: :users_hobby_delete
   #communities
   delete 'users/:id/hobby/:hobby_id/community/:community_id', to: 'users#community_delete', as: :users_community_delete
   #records
   post 'users/:id/hobby/:hobby_id/record', to: 'users#record_create', as: :users_record
   delete 'users/:id/hobby/:hobby_id/record', to: 'users#record_delete', as: :users_record_delete
   #cancel
   get '/users/cancel/show', to: 'users#cancel_show', as: :users_cancel_show
   delete '/users/cancel/show', to: 'users#cancel_delete', as: :users_cancel_delete

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    if user.try(:admin?)
        can :access, :rails_admin
        can :manage, :all
    #   else
    #     can :read, :all
    end
  end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board_comment.rb
class BoardComment < ApplicationRecord
  belongs_to :community
  belongs_to :user

  validates :comment, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  attachment :image

  has_many :hobbies

  validates :category, presence: true
end

app/models/community.rb
class Community < ApplicationRecord
  has_many :board_comments
  has_many :users_communities
  has_many :users, through: :users_communities
  belongs_to :hobby

  validates :name, presence: true
  validates :level, presence: true
  validates :introduction, length: {in: 2..20}, presence: true
end

app/models/first_step.rb
class FirstStep < ApplicationRecord
  belongs_to :hobby

  validates :item, presence: true
  validates :cost, presence: true
  validates :introduction, presence: true
end

app/models/hobbies_rating.rb
class HobbiesRating < ApplicationRecord
  belongs_to :hobby
  belongs_to :rating

  validates :point, presence: true
end

app/models/hobby.rb
class Hobby < ApplicationRecord

  attachment :image

  has_many :users_hobbies, dependent: :destroy
  has_many :users, through: :users_hobbies
  has_many :records
  has_many :communities
  belongs_to :category
  has_many :hobbies_ratings
  has_many :ratings, through: :hobbies_ratings
  has_one :first_step

end

app/models/rating.rb
class Rating < ApplicationRecord
  has_many :hobbies_ratings
  has_many :hobbies, through: :hobbies_ratings

  validates :name, presence: true
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
  belongs_to :hobby

  validates :time, presence: true
  validates :date, presence: true
  validates :comment, length: {in: 0..50}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attachment :image

  has_many :users_hobbies
  has_many :hobbies, through: :users_hobbies
  has_many :users_communities
  has_many :communities, through: :users_communities
  has_many :records
  has_many :board_comments

  validates :name, presence: true
  validates :age, presence: true
  validates :sex, presence: true
  validates :job, presence: true
  validates :address, presence: true
  validates :email, presence: true
  validates :introduction, length: { maximum: 200 }
end

app/models/users_community.rb
class UsersCommunity < ApplicationRecord
  belongs_to :user
  belongs_to :community
end

app/models/users_hobby.rb
class UsersHobby < ApplicationRecord
  belongs_to :user
  belongs_to :hobby
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
before_action :authenticate_user!, :only => [:show, :index]
  def index
    @hobby = Hobby.find(params[:id])
    @communities = Community.where(hobby_id: @hobby.id).page(params[:page]).per(10)
  end

  def new
    @hobby = Hobby.find(params[:id])
    @community = Community.new
  end

  def create
    hobby = Hobby.find(params[:id])
    community = Community.new(community_params)
    community.hobby_id = hobby.id
    community.user_id = current_user.id
    if community.save
      flash[:notice] = "チャレンジを追加しました"
      redirect_to community_index_path(hobby)
    else
      flash[:notice] = "エラー：入力に誤りがあります"
      redirect_to community_new_path
    end
  end

  def delete
    community = Community.find(params[:community_id])
    uc = UsersCommunity.where(community_id: community.id)
    if community.destroy
      uc.each do |uc|
        uc.destroy
      end
      flash[:notice] = "趣味を削除しました"
      redirect_to community_index_path
    else
      flash[:notice] = "趣味の削除に失敗しました"
      redirect_to community_index_path
    end
  end

  def show
    @community = Community.find(params[:id])
    @boards = BoardComment.where(community_id: @community.id).order(id: "ASC").page(params[:page]).per(20)
    @board = BoardComment.new
  end

  def add
    community = Community.find(params[:id])
    user = current_user
    uc = UsersCommunity.new
    uc.user_id = user.id
    uc.community_id = community.id
    if uc.save
      flash[:notice] = "チャレンジに追加しました"
      redirect_to community_show_path
    else
      flash[:notice] = "エラー：ログインしてください"
      redirect_to community_show_path
    end
  end

  private
  def community_params
    params.require(:community).permit(:hobby_id, :name, :level, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/helpers/hobbies_helper.rb
module HobbiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/matching_helper.rb
module MatchingHelper
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/communities/index.html.erb
<div class="container">
    <div class="row">
    	<div class="col-lg-4">
    	</div>
       	<div class="col-lg-4">
      		<h3>チャレンジ一覧</h3>
      	</div>
	    <div class= "col-lg-3">
      		<%= link_to "新規チャレンジ追加", community_new_path, class: "btn btn-primary btn-xs" %>
      	</div>
    </div>
<br>
<br>
	<div class="row justify-content-center">
		<table class='table'>
			<thead>
		        <tr>
		          	<th>チャレンジ名</th>
		          	<th>難易度</th>
		          	<th>紹介文</th>
		          	<th>作成日</th>
		          	<th>詳細</th>
		          	<th></th>
		        </tr>
		    </thead>
		   	<% @communities.each do |community| %>
		    <tbody>
		        <tr>
		        	<td><%= community.name %></td>
		          	<td><%= community.level %></td>
		          	<td><%= community.introduction %></td>
		          	<td><%= community.created_at.strftime('%Y/%m/%d') %></td>
		          	<td><%= link_to "詳細", community_show_path(community), class: "btn btn-primary btn-xs" %></td>
		          	<td><%if current_user.id == community.user_id or current_user.admin? %>
		          		<%= link_to "削除", community_delete_path(community_id: community.id),method: :delete, class: "btn btn-light btn-xs", "data-confirm" => "Are you sure?" %>
		          	<% end %></td>
		        </tr>
		    </tbody>
		    <% end %>
		</table>
	<%= paginate @communities %>
  	</div>
</div>

app/views/communities/new.html.erb
<div class="container">
  <%= flash[:notice] %>
  <div class="row justify-content-md-center mb-lg-5">
    <div class="col-md-10">
    <h2>新規チャレンジ登録</h2><br>
    <%= form_for @community, url: community_create_path(@hobby) do |f| %>
    	<div class="form-group">
          <%= f.label :チャレンジ名 %><br>
          <%= f.text_field :name %>
        </div>
        <div class="form-group">
		  <%= f.label :難易度 %><br />
		  <%= f.select :level, [["初級", "初級"], ["中級", "中級"], ["上級", "上級"]],:prompt => "選択" %>
		</div>

		<div class="form-group">
          <%= f.label :説明文 %><br>
          <%= f.text_field :introduction %>
        </div>
    	<div class="form-action">
        <%= f.submit "登録", class: "btn btn-primary btn-xs" %>
    	</div>
    <% end %>
    </div>
  </div>
</div>

app/views/communities/show.html.erb
<main>
<% if flash[:notice] %>
<%= flash[:notice] %>
<% end %>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-3">
    		<div class="hobby_image">
       		<%= attachment_image_tag @community.hobby, :image, :fill, 250, 250, :size => "250x250", fallback: "no-category-image.jpg" %>
      	</div>
      </div>
      <div class="col-lg-5">
        <h5 class="community_name">チャレンジ名 &nbsp <u><%= @community.name %></u></h5><br>
        <h5>紹介文</h5>
        <div class="card">
          <div class="card-body">
            <%= @community.introduction %>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <%= link_to "チャレンジに追加する", community_add_path(@community), method: :post, class: "btn btn-primary btn-xs" %>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row justify-content-center">
      <h3>チャレンジ掲示板</h3>
    </div>
    <br>
    <div class="row justify-content-center">
      <div class="col-lg-12">
        <table class = "table">
        <% @boards.each.with_index do |board, i| %>
          <tr>
            <td></td>
            <td><%= i+1 %></td>
            <td><%= board.comment %></td>
            <td><%= link_to user_path(board.user.id) do %><%= board.user.name %>さん<% end %></td>
            <td><%= board.created_at.strftime('%Y/%m/%d') %></td>
            <td><% if current_user.id == board.user.id or current_user.admin? %>
            <%= link_to '削除', board_comment_delete_path(@community.id, :board_comment_id => board.id), method: :delete, class: 'btn btn-primary', "data-confirm" => "Are you sure?" %></td>
          <% end %>
          </tr>
        <% end %>
        </table>
      </div>
    <%= paginate @boards %>
    </div>
    <%= form_for @board, url: board_comment_add_path(@community.id) do |f| %>
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <h5>コメント</h5>
        <div class="field">
          <%= f.text_field :comment, :size=>"60x10", placeholder: "コメント" %>
        </div>
        <br>
      </div>
    </div>
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <div class="action">
          <%= f.submit "投稿する", class: "btn btn-primary btn-xs" %>
        <% end %>
      </div>
    </div>
  </div>
</main>