config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # categories
  get 'categories', to: 'categories#index', as: :category_index
  get 'categories/:id', to: 'categories#show', as: :category_show

  # hobbies
  get 'hobbies/:id', to: 'hobbies#show', as: :hobby_show
  post 'hobbies/:id', to: 'hobbies#add', as: :hobby_add

  #communities
  get 'hobbies/:id/communities', to: 'communities#index', as: :community_index
  get 'hobbies/:id/communities/new', to: 'communities#new', as: :community_new
  post 'hobbies/:id/communities/create', to: 'communities#create', as: :community_create
  delete 'hobbies/:id/communities/delete', to: 'communities#delete', as: :community_delete
  get 'community/:id', to: 'communities#show', as: :community_show
  post 'community/:id', to: 'communities#add', as: :community_add
   #board_comments
   post 'community/:id/board_comments', to: 'board_comments#add', as: :board_comment_add
   delete 'community/:id/board_comments', to: 'board_comments#delete', as: :board_comment_delete

  #matchings
  get 'matching', to: 'matching#show', as: :matching_show
  get 'matching/result', to: 'matching#result_show', as: :matching_result_show

  #rankings
  get 'rankings', to: 'rankings#index', as: :ranking_index

  # home
  root to: 'home#index'

  # users
  resources :users, only: [:show, :edit, :update]
   #hobbies
   get 'users/:id/hobby/:hobby_id', to: 'users#hobby_index', as: :users_hobby
   delete 'users/:id/hobby/:hobby_id', to: 'users#hobby_delete', as: :users_hobby_delete
   #communities
   delete 'users/:id/hobby/:hobby_id/community/:community_id', to: 'users#community_delete', as: :users_community_delete
   #records
   post 'users/:id/hobby/:hobby_id/record', to: 'users#record_create', as: :users_record
   delete 'users/:id/hobby/:hobby_id/record', to: 'users#record_delete', as: :users_record_delete
   #cancel
   get '/users/cancel/show', to: 'users#cancel_show', as: :users_cancel_show
   delete '/users/cancel/show', to: 'users#cancel_delete', as: :users_cancel_delete

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    if user.try(:admin?)
        can :access, :rails_admin
        can :manage, :all
    #   else
    #     can :read, :all
    end
  end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board_comment.rb
class BoardComment < ApplicationRecord
  belongs_to :community
  belongs_to :user

  validates :comment, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  attachment :image

  has_many :hobbies

  validates :category, presence: true
end

app/models/community.rb
class Community < ApplicationRecord
  has_many :board_comments
  has_many :users_communities
  has_many :users, through: :users_communities
  belongs_to :hobby

  validates :name, presence: true
  validates :level, presence: true
  validates :introduction, length: {in: 2..20}, presence: true
end

app/models/first_step.rb
class FirstStep < ApplicationRecord
  belongs_to :hobby

  validates :item, presence: true
  validates :cost, presence: true
  validates :introduction, presence: true
end

app/models/hobbies_rating.rb
class HobbiesRating < ApplicationRecord
  belongs_to :hobby
  belongs_to :rating

  validates :point, presence: true
end

app/models/hobby.rb
class Hobby < ApplicationRecord

  attachment :image

  has_many :users_hobbies, dependent: :destroy
  has_many :users, through: :users_hobbies
  has_many :records
  has_many :communities
  belongs_to :category
  has_many :hobbies_ratings
  has_many :ratings, through: :hobbies_ratings
  has_one :first_step

end

app/models/rating.rb
class Rating < ApplicationRecord
  has_many :hobbies_ratings
  has_many :hobbies, through: :hobbies_ratings

  validates :name, presence: true
end

app/models/record.rb
class Record < ApplicationRecord
  belongs_to :user
  belongs_to :hobby

  validates :time, presence: true
  validates :date, presence: true
  validates :comment, length: {in: 0..50}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attachment :image

  has_many :users_hobbies
  has_many :hobbies, through: :users_hobbies
  has_many :users_communities
  has_many :communities, through: :users_communities
  has_many :records
  has_many :board_comments

  validates :name, presence: true
  validates :age, presence: true
  validates :sex, presence: true
  validates :job, presence: true
  validates :address, presence: true
  validates :email, presence: true
  validates :introduction, length: { maximum: 200 }
end

app/models/users_community.rb
class UsersCommunity < ApplicationRecord
  belongs_to :user
  belongs_to :community
end

app/models/users_hobby.rb
class UsersHobby < ApplicationRecord
  belongs_to :user
  belongs_to :hobby
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/hobbies_helper.rb
module HobbiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/matching_helper.rb
module MatchingHelper
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bd-navbar shadow fixed-top py-3">
    <a class="navbar-brand mb-0 h1 ml-4" href="<%= root_path %>">QUAINT</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto ml-5">
        <!-- ログイン時 -->
        <% if user_signed_in? %>
          <li>
            <a class="nav-link" href="<%= matching_show_path %>">
              趣味マッチング
            </a>
          </li>
          <li>
            <a class="nav-link" href="<%= category_index_path %>">
              カテゴリー別趣味
            </a>
          </li>
          <li>
            <a class="nav-link" href="<%= ranking_index_path %>">
              ランキング
            </a>
          </li>
          <li>
            <a class="nav-link" href="<%= user_path(current_user.id) %>">
              マイページ
            </a>
          </li>
          <li>
            <a>
            <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link' do %>
              <span>ログアウト</span>
            <% end %>
          </li>
          <li>
            <a class="nav-link disabled" href="#">
              <%= current_user.name %>
            </a>
          </li>
          <!--  未ログイン -->
        <% else %>
            <a class="nav-link" href="<%= matching_show_path %>">
              趣味マッチング
            </a>
            <a class="nav-link" href="<%= category_index_path %>">
              カテゴリー別趣味
            </a>
            <a class="nav-link" href="<%= ranking_index_path %>">
              ランキング
            </a>
            <a class="nav-link" href="<%= new_user_session_path %>">
              ログイン
            </a>
            <a class="nav-link" href="<%= new_user_registration_path %>">
              新規会員登録
            </a>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_sidebar.html.erb
<div class="profile">
  <% if current_user.id == user.id or current_user.admin? %>
    <div class="row justify-content-center">
      <div class="col-lg-3">
        <div class="user_image">
          <%= attachment_image_tag current_user, :image, :fill, 250, 250, :size => "250x250", fallback: "no-user-image.jpg" %>
        </div>
      </div>
      <div class="col-lg-5">
        <div class="card">
          <div class="card-body">
            <h5 class="user_name">ユーザー名 &nbsp <u><%= current_user.name %></u></h5><br>
            <h5 class="user_information"><%= current_user.address %>／<%= current_user.age %>代／<%= current_user.sex %></h5>
          </div>
        </div>
        <br>
        <div class="card">
          <div class="card-body">
            <h5 class="user_introduction"><%= current_user.introduction %></h5>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <%= link_to "プロフィール編集", edit_user_path(current_user.id), class: "btn btn-primary btn-xs" %><br>
      </div>
    </div>
  <!-- 他ユーザー -->
  <% else %>
    <div class="row justify-content-center">
      <div class="col-lg-3">
        <div class="user_image">
          <%= attachment_image_tag user, :image, :fill, 250, 250, :size => "250x250", fallback: "no-user-image.jpg" %>
        </div>
      </div>
      <div class="col-lg-5">
        <div class="card">
          <div class="card-body">
        <h5 class="user_name">ユーザー名 &nbsp <u><%= user.name %></u></h5><br>
        <h5 class="user_information"><%= user.address %>／<%= user.age %>代／<%= user.sex %></h5>
          </div>
        </div>
        <br>
        <div class="card">
          <div class="card-body">
            <%= user.introduction %>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QUAINT</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
  <footer class="container-fluid bg-light">
    <div class="row">
      <div class="col-4 d-flex">
        <p class="text-secondary">© 2019 Copyright Text</p>
      </div>
    </div>
  </footer>
</html>